# Generated by Django 3.1.5 on 2021-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0005_vote_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='model_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
