# Generated by Django 3.1.5 on 2021-01-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0006_vote_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_answered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='selected_answer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
