# Generated by Django 3.1.5 on 2021-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_auto_20210113_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='selected_answer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
