# Generated by Django 3.1.5 on 2021-01-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0009_auto_20210127_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
